
import { Player, BoardTile } from './types';

export const createInitialPlayers = (playerName: string, playerAddress: string): Player[] => [
  { id: 1, name: playerName, money: 2000, position: 0, nfts: [], inJail: false, jailTurns: 0, tokenColor: 'bg-red-500', isBot: false, walletAddress: playerAddress },
  { id: 2, name: 'Satoshi', money: 2000, position: 0, nfts: [], inJail: false, jailTurns: 0, tokenColor: 'bg-blue-500', isBot: true },
];

export const BOARD_TILES: BoardTile[] = [
  { type: 'go', name: 'GO' },
  { type: 'market', name: 'Market', marketId: '0' },
  { type: 'community-chest', name: 'Community Chest' },
  { type: 'market', name: 'Market', marketId: '1' },
  { type: 'tax', name: 'Gas Fee', amount: 200 },
  { type: 'market', name: 'Market', marketId: '2' },
  { type: 'market', name: 'Market', marketId: '3' },
  { type: 'chance', name: 'Chance' },
  { type: 'market', name: 'Market', marketId: '4' },
  { type: 'market', name: 'Market', marketId: '5' },
  { type: 'jail', name: 'Jail / Just Visiting' },
  { type: 'market', name: 'Market', marketId: '6' },
  { type: 'tax', name: 'Validator Fee', amount: 150 },
  { type: 'market', name: 'Market', marketId: '7' },
  { type: 'market', name: 'Market', marketId: '8' },
  { type: 'market', name: 'Market', marketId: '9' },
  { type: 'market', name: 'Market', marketId: '10' },
  { type: 'community-chest', name: 'Community Chest' },
  { type: 'market', name: 'Market', marketId: '11' },
  { type: 'market', name: 'Market', marketId: '12' },
  { type: 'free-parking', name: 'Airdrop' },
  { type: 'market', name: 'Market', marketId: '13' },
  { type: 'chance', name: 'Chance' },
  { type: 'market', name: 'Market', marketId: '14' },
  { type: 'market', name: 'Market', marketId: '15' },
  { type: 'market', name: 'Market', marketId: '16' },
  { type: 'market', name: 'Market', marketId: '17' },
  { type: 'market', name: 'Market', marketId: '18' },
  { type: 'tax', name: 'Bridge Fee', amount: 150 },
  { type: 'market', name: 'Market', marketId: '19' },
  { type: 'go-to-jail', name: 'Go To Rugpull' },
  { type: 'market', name: 'Market', marketId: '20' },
  { type: 'market', name: 'Market', marketId: '21' },
  { type: 'community-chest', name: 'Community Chest' },
  { type: 'market', name: 'Market', marketId: '22' },
  { type: 'market', name: 'Market', marketId: '23' },
  { type: 'chance', name: 'Chance' },
  { type: 'market', name: 'Market', marketId: '24' },
  { type: 'tax', name: 'Exchange Fee', amount: 100 },
  { type: 'market', name: 'Market', marketId: '25' },
];
